### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by No-Github** [wjlab/DataMiner#1]
1. 密码中带 # 号 好像解析不了
2. 部分oracle需要自定义TNS:listener

工具很好用,多谢师傅分享

**Comment by N0body007** [comment]
好的，后续优化一下

**Comment by N0body007** [comment]
工具最新版目前已支持Oracle TNS登录方式；对于第一个问题，工具可以正常解析带 # 号的密码，如果后续还碰到了这种情况，你可以先加我的twitter，将对应的信息发给我，感谢支持使用
