### ISSUE TITLE
是不是不能指定库名字

### ISSUE THREAD

**Issue by Mayter** [wjlab/DataMiner#2]
而且有报错，主要不能选择库名字，要不然试试别的库
![text](https://github.com/wjlab/DataMiner/assets/6148807/d25072bf-8e32-4523-9ced-e0ef868fd987)

**Comment by N0body007** [comment]
"SD"是全部数据库取样模块，不能够对指定数据库取样，可以使用"ST" 指定数据库单表进行取样；
![图片](https://github.com/wjlab/DataMiner/assets/56355035/a31878fe-1d93-40c7-b0d4-7a82498b8b61)
上方的Error信息可以全部发出来吗，敏感的地方可以使用xxxx进行代替

**Comment by Mayter** [comment]
> "SD"是全部数据库取样模块，不能够对指定数据库取样，可以使用"ST" 指定数据库单表进行取样； ![图片](https://user-images.githubusercontent.com/56355035/267207752-a31878fe-1d93-40c7-b0d4-7a82498b8b61.png) 上方的Error信息可以全部发出来吗，敏感的地方可以使用xxxx进行代替

没有别的错误了，就这些我能看到的也是这些东西，取表还不如一个点着看呢，因为只看某个关键核心库啊，不看别的库

**Comment by N0body007** [comment]
好的，后续加一个对指定数据库取样的功能

**Comment by Mayter** [comment]
要是在加一个postgresql就行了，这个选在用的也挺多的

**Comment by N0body007** [comment]
可以

**Comment by N0body007** [comment]
最新版本已支持对指定单一数据库的取样和postgre数据库的支持
