### ISSUE TITLE
mysql不支持指定数据库取样吗？

### ISSUE THREAD

**Issue by perkupup** [wjlab/DataMiner#5]
mysql不支持指定数据库取样吗？
![Uploading image.png…]()

**Comment by perkupup** [comment]
![微信图片_20240605085520](https://github.com/wjlab/DataMiner/assets/98009359/6964517d-7790-4289-93f0-fcc6a2c53138)

**Comment by N0body007** [comment]
支持的，上方的命令少打了一个'S'，应该为 ' SSD '
![图片](https://github.com/wjlab/DataMiner/assets/56355035/6017acbd-d20f-4ebe-b785-d55db034fab9)
![图片](https://github.com/wjlab/DataMiner/assets/56355035/2fd1f165-61d7-4581-8e00-b754b768637d)

**Comment by perkupup** [comment]
> 支持的，上方的命令少打了一个'S'，应该为 ' SSD ' ![图片](https://private-user-images.githubusercontent.com/56355035/336711119-6017acbd-d20f-4ebe-b785-d55db034fab9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1Njk5NTEsIm5iZiI6MTcxNzU2OTY1MSwicGF0aCI6Ii81NjM1NTAzNS8zMzY3MTExMTktNjAxN2FjYmQtZDIwZi00ZWJlLWI3ODUtZDU1ZGIwMzRmYWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA2NDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MjM4MDMyYmJiMjM3NjY5ZGFjNTAxYmU5MzMwMjUzYWQ0NGRkZWJhMWQ2OGFkYTUzZDM0NjgwMGIyYmNhOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G7CKMyC0iBCpDqsQ_fb1ZeANn5E6l76HBdmeO9noxHI) ![图片](https://private-user-images.githubusercontent.com/56355035/336711568-2fd1f165-61d7-4581-8e00-b754b768637d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1Njk5NTEsIm5iZiI6MTcxNzU2OTY1MSwicGF0aCI6Ii81NjM1NTAzNS8zMzY3MTE1NjgtMmZkMWYxNjUtNjFkNy00NTgxLThlMDAtYjc1NGI3Njg2MzdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA2NDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NWJmYTMxYWJmZWFjY2Y3NGY3MDc1MDQ5ZGM5ZTZhYjE2NTc3YTBkOGUyYjQ0NDA2ZWUzYTI5YTFjMDM5OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HXHFRxxpZT1_mx-eOwJ-_rJJLT8bfWhYiZ6YB0WQX-M)

感谢！！
